version: '3.8'

services:
  whoami:
    image: traefik/whoami
    labels:
      - traefik.http.routers.whoami.rule=Host(`whoami.localhost`)
    networks:
      - vmp-net

networks:
  vmp-net:
    external: true
