version: '3.8'

services:
  reverse-proxy:
    image: traefik:v2.9
    command:
      - --api.insecure=true
      - --providers.docker
      - --accesslog=true
    ports:
      - 80:80
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - vmp-net
    labels:
      - traefik.http.routers.traefik.rule=Host(`traefik.localhost`)

networks:
  vmp-net:
    external: true

